language: ruby
rvm:
- 2.5
notifications:
  email: false
cache: bundler
script: "./script/cibuild"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_deploy:
- openssl aes-256-cbc -K $encrypted_cd964dde258e_key -iv $encrypted_cd964dde258e_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet -e "ssh -p $SCP_PORT -o 'StrictHostKeyChecking=no'" $TRAVIS_BUILD_DIR/_site/* $SCP_USER@rubensworks.net:$SCP_LOCATION
  on:
    branch: master
